### PR TITLE
update set relationshipType

### PR DESCRIPTION
**Pull request by ahdinosaur**
wasn't feeling the existing set relType, so made a few changes. @simontegg thoughts?

if keen, i'll fix up the rest of the data before merging.

### CODE REVIEW

**Comment by simontegg** [comment]
I went with subgroup because its more [popular](https://books.google.com/ngrams/graph?content=sub-group%2Cchild+group%2Csubgroup%2C+child-group&year_start=1800&year_end=2008&corpus=15&smoothing=3&share=&direct_url=t1%3B%2Csub%20-%20group%3B%2Cc0%3B.t1%3B%2Cchild%20group%3B%2Cc0%3B.t1%3B%2Csubgroup%3B%2Cc0%3B.t1%3B%2Cchild%20-%20group%3B%2Cc0) and less ambiguous. Although I understand there's a lack of consistency with `parent-group`

**Comment by ahdinosaur** [comment]
so, subgroup and supergroup? or subset and superset?

**Comment by simontegg** [comment]
Which is more important - consistency between terms or term comprehension?

**Comment by ahdinosaur** [comment]
i reckon term comprehension is most important and with that in mind inconsistent terms are more difficult to comprehend.

**Comment by ahdinosaur** [comment]
or part and whole.

**Comment by simontegg** [comment]
Comprehension by users or by developers? My hunch is that term inconsistency  is much less of a problem for users. They don't think about a relationship as having two roles etc. They just look at the role name, and understand or not understand what its supposed to mean.

**Comment by ahdinosaur** [comment]
in the case of relationship roles, the `id`s matter for developers, the `labels` and such matter for users. links are our attempt to fill the comprehension gap between relationships and roles so users can think in terms of links.

regarding this PR, my primary motivation is to change the `id`s of the set relationship roles, `parent-group` and `subgroup` for no reason other than they don't vibe with me and i'm one of only two people at the moment who has to deal with it, so i'm gonna change it to one of:
- parent / child
- supergroup / subgroup
- superset / subset
- whole / part

@simontegg which one is your favorite?

if we like the existing labels, i'm fine to keep them as they are. i'll update the description but we don't use that anywhere user-facing.

**Comment by simontegg** [comment]
As you've mentioned, I think the user-facing labels should be `parent-group` and `subgroup` as these are the most commonly understood, least ambiguous terms. 

My favourite from those options is `parent` and `child` or perhaps `parent-node` and `child-node` https://en.wikipedia.org/wiki/Parent_(disambiguation) (if we're gonna use technical terms, go the whole hog)

Meta: achieving technical term internal consistency trades-off with user-facing vs developer-facing term consistency.

**Pull request closed without merging**
