### PR TITLE
new labels and links

### PR DESCRIPTION
**Pull request by simontegg**

### CODE REVIEW

**Comment by ahdinosaur** [comment]
sweet! :pineapple:

**Comment by ahdinosaur** [comment]
this broke production:

```
/app/src/node_modules/api/index.js:0
(function (exports, require, module, __filename, __dirname) { var express = re

TypeError: Cannot read property 'Model' of undefined
    at Function.assign.new (/app/src/node_modules/base/model.js:118:25)
    at /app/src/node_modules/api/index.js:107:27
    at Array.map (native)
    at /app/src/node_modules/api/index.js:106:10
    at /app/node_modules/pull-stream/maybe.js:41:9
    at /app/node_modules/pull-stream/sinks.js:11:20
    at /app/node_modules/pull-stream/throughs.js:21:7
    at /app/node_modules/fs-db/lib/parse.js:18:11
    at process._tickCallback (node.js:355:11)
```

happens because the links are objects without a `@type` that corresponds to a type in [the `types` module](https://github.com/holodex/app/blob/master/src/node_modules/types/index.js).

**Comment by ahdinosaur** [comment]
aaaaaaand... we're back. :tada:

**Comment by simontegg** [comment]
so create a @type ?

**Comment by ahdinosaur** [comment]
yes, maybe `LinkType`? so that means make a `link-type` module with a `Model` exported in it's `index.js` and then add it to the`types` module. let me know if you want help on any of this.

**Pull request merged**
